name: deploy
on:
  push:
    branches:
      - master  # o ajusta a tu rama
jobs:
  push_to_registry:
    environment: dockerhub
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: firstbuffalo/angular
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: firstbuffalo/angular:v1.0.7.1
          #tags: ${{ steps.meta.outputs.tags }}
          #labels: ${{ steps.meta.outputs.labels }}

      - name: Send to minikube
        uses: steebchen/kubectl@v2.0.0
        with:
         config: ${{secrets.KUBE_CONFIG_DATA}}
         command: set image --record deployment/my-app container=${{ github.repository }}:v1.0.7.1


      